//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamos
    {
        public int id_prestamo { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> id_libro { get; set; }
        public string fecha_prestamo { get; set; }
        public string fecha_entrega { get; set; }
        public string comentarios { get; set; }
    
        public virtual Libros Libros { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
